### ISSUE TITLE
add button to switch between saving video and image

### ISSUE THREAD

**Issue by codetricity** [caitlynbakery/09_theta_image_save#4]
current code saves the last video.

![image](https://user-images.githubusercontent.com/5799860/179040675-3bd2b7d8-3bf8-41fe-b009-8cdfe435df80.png)

This appears to work fine.

Switch code so the default is image.

```dart
              var bodyMap = {
                'name': 'camera.listFiles',
                'parameters': {
                  'fileType': 'image',
                  'startPosition': 0,
                  'entryCount': 1,
                  'maxThumbSize': 0,
                  '_detail': true,
                }
```

You must also adjust the `GallerySaver.saveVideo()` to `GallerySaver.saveImage()`

Using Gallery, it seems to work.

![image](https://user-images.githubusercontent.com/5799860/179042327-720375ae-735a-4e4c-b262-48cc8777c90c.png)

![image](https://user-images.githubusercontent.com/5799860/179042407-e6348fb1-4ab1-418c-a1b8-bc9ddc22820b.png)

**Comment by caitlynbakery** [comment]
Alright, I added an additional button to the screen. 

![savingapp](https://user-images.githubusercontent.com/22283010/179246697-e8278372-3dc7-4366-956a-a1a50651c0b9.png)

I also had the application working with Google Photos.

![googlephotos](https://user-images.githubusercontent.com/22283010/179246897-8afd7d73-a67c-42be-9728-b5a1b52f74eb.png)
